-- Chunk: tips + tip_sections
-- tips/trinidad-and-tobago
INSERT INTO "tips" ("id", "slug", "country", "country_code", "state", "title", "description", "status", "published_at") VALUES ($s$0e623603-f1fa-4e99-971a-dd8661ccae7f$s$, $s$trinidad-and-tobago$s$, $s$Trinidad and Tobago$s$, $s$TT$s$, NULL, $s$Trinidad and Tobago Travel Tips$s$, NULL, $s$published$s$, '2026-04-12T21:51:34.489Z'::timestamptz);
INSERT INTO "tip_sections" ("tip_id", "section_key", "content", "enabled", "position") VALUES
  ($s$0e623603-f1fa-4e99-971a-dd8661ccae7f$s$, $s$essential_tips$s$, $s$<p>🇹🇹  <strong>Trinidad - Insider Tips ⁉️</strong></p> <p>☀️ <strong>Time to Visit</strong> The best time to visit is from December to April for the dry season. While it's wise to avoid hurricane season (June-November), we took a chance in early October and were lucky enough to enjoy fantastic weather! 🤞</p> <p>✈️ <strong>Flights</strong> - Caribbean Airlines offers convenient morning flights from NYC, giving you an entire afternoon to explore this vibrant island nation.</p> <p>⏳ <strong>Focusing Your Time</strong> - We decided to spend 10 days exploring the twin 🏝️islands of Trinidad & Tobago, splitting our time evenly between them. Looking back, we wholeheartedly recommend focusing more on Tobago. This smaller island boasts breathtaking beaches, lush rainforests, and a more relaxed pace. While both islands offer unique experiences, Tobago truly captivated our hearts.</p> <p>🏌️ <strong>Guided tour</strong> - When visiting the La Brea Tar Pits, you'll encounter local guides offering their services. These knowledgeable guides provide fascinating insights into the history and paleontology of the site, enriching your experience. But be sure to agree on a fee beforehand for a smooth and enjoyable visit.</p> <p>ℹ️ <strong>Driving tips</strong> (in case you decide to rent a car) - Driving in the islands presents unique challenges. Firstly, remember to drive on the left-hand side of the road. Secondly, be prepared for sudden stops by locals. Be cautious, as most roads lack proper shoulders and usually have dips or trenches. For your safety, we recommend driving during daylight hours.</p> <p><strong>Tobago: Visiting Nylon pool, and Buccoo</strong> - We initially considered booking our Nylon Pool and Buccoo Reef tour through Viator, but we quickly discovered that many local operators offer similar experiences at significantly lower prices. We booked our tour through a hotel recommendation, but exploring the beach itself will likely reveal a variety of tour operators offering competitive rates.</p> <p>💲 <strong>Currency</strong>: Trinidad and Tobago Dollar (TTD) - US dollars widely accepted.</p> <p>🗣️ <strong>Language</strong>: English is the official language, but you'll hear lots of local slang and expressions.</p> <p>💁 <strong>Tipping</strong>: 10-15% at restaurants, round up for taxi drivers</p> <p>🛜 <strong>Internet</strong>: You'll find 🛜 at most hotels and cafes. For consistent connectivity, consider grabbing a local SIM card or purchasing an international package from your home provider</p>$s$, TRUE, 0),
  ($s$0e623603-f1fa-4e99-971a-dd8661ccae7f$s$, $s$budget_planning$s$, NULL, FALSE, 1),
  ($s$0e623603-f1fa-4e99-971a-dd8661ccae7f$s$, $s$food_dining$s$, $s$<p>🇹🇹🌶️ <strong>Food</strong>: Prepare your taste for a vibrant adventure in Trinidad and Tobago, where the food is as rich and diverse as its culture! This twin-island nation offers a tantalizing array of dishes and a delicious fusion of African, Indian, Creole, and even Chinese influences.  Prepare your taste buds for a vibrant adventure in Trinidad and Tobago, where the food is as rich and diverse as its culture! This twin-island nation offers a tantalizing array of dishes and a delicious fusion of African, Indian, Creole, and even Chinese influences. One absolute must-try you'll find at nearly every street corner is Doubles. These are deceptively simple yet incredibly flavorful street foods. We quickly became obsessed, grabbing them from street stands whenever we could.</p>$s$, TRUE, 2),
  ($s$0e623603-f1fa-4e99-971a-dd8661ccae7f$s$, $s$transportation$s$, $s$<p>🚌 <strong>Transportation</strong> - 🚕'Maxi Taxis' or 🛻'PHs': These are shared rides where locals stand by the roadside and flag down passing vehicles. While affordable, they may not be the safest option for tourists, especially outside city limits.  Formal 🚖Taxis are typically booked through your 🏨hotel. While more expensive, they offer a safer and more reliable option for getting around.</p> <p>🚗 <strong>Renting a car</strong> - Most sites and even locals advise against renting a car due to concerns about driving conditions and local culture. However, after experiencing the limitations of public transportation and the high cost of taxis, we decided to rent a car. This was the best decision, allowing us to explore the island at our own pace. ⚠️A crucial tip: Always take 📷photos of the rental car, including the wheels, to avoid any disputes upon return.</p>$s$, TRUE, 3),
  ($s$0e623603-f1fa-4e99-971a-dd8661ccae7f$s$, $s$accommodation$s$, $s$<p><strong>Trinidad</strong>:</p> <p>Convenience to attractions was our top priority. We found that staying near Queen's Park Savannah was a game-changer. This massive green space isn't just great for a leisurely walk; it's also centrally located, giving you easy access to so many parts of the city. Look for hotels surrounding the Savannah – you'll be right at the heart of the action, ready to explore! our hotel, [The BRIX, Autograph Collection](https://expedia.com/affiliate/Zm1VD21). We selected this 🏨for its upscale accommodations, great deal, and proximity to key attractions.</p> <p>If you're opting for private rentals  🏠 or guesthouses, make sure they have good security features like strong locks and grills, especially if they're in isolated locations.</p> <p><strong>Tobago</strong>:</p> <p>We booked [hotel](https://expedia.com/affiliate/ghdYxIR) at Crown Point, the most developed area on the island, close to the airport (ANR Robinson International Airport) and Pigeon Point Beach with easy access to restaurants, bars, and popular tourist activities.</p> <p>If renting a private villa, especially in more isolated areas, ensure it has robust security measures.</p>$s$, TRUE, 4),
  ($s$0e623603-f1fa-4e99-971a-dd8661ccae7f$s$, $s$safety_health$s$, $s$<p><strong>Trinidad</strong>:</p> <p>Walking around 🚶Many roads lack proper curbs and may have sudden dips or trenches. Avoid walking at night, especially in less populated areas, and always be aware of your surroundings, as vehicles drive on the left-hand side of the road.</p> <p>Avoid high-crime areas: Steer clear of neighborhoods like Laventille, Morvant, Sea Lots, Beetham, and parts of East Port of Spain (especially south Charlotte Street and Piccadilly Street), particularly after dark.</p> <p>Be cautious at night: Even in safer areas, avoid walking alone in poorly lit or isolated spots, including certain parts of downtown and Queen's Park Savannah after dark.</p> <p><strong>Tobago</strong>:</p> <p>While Tobago is generally safer than Trinidad, common sense precautions apply. Avoid walking alone on deserted beaches or isolated areas, especially after dark.</p> <p>Be very cautious about booking isolated private villas 🏠 without confirmed, adequate 24-hour security.</p>$s$, TRUE, 5);
-- tips/united-states-massachusetts
INSERT INTO "tips" ("id", "slug", "country", "country_code", "state", "title", "description", "status", "published_at") VALUES ($s$f8c34df2-8f5d-4d22-ac9c-c58ef455547e$s$, $s$united-states-massachusetts$s$, $s$United States$s$, $s$US$s$, $s$Massachusetts$s$, $s$United States, Massachusetts Travel Tips$s$, $s$Essential tips for traveling in United States, Massachusetts$s$, $s$published$s$, '2026-04-12T21:51:34.489Z'::timestamptz);
INSERT INTO "tip_sections" ("tip_id", "section_key", "content", "enabled", "position") VALUES
  ($s$f8c34df2-8f5d-4d22-ac9c-c58ef455547e$s$, $s$essential_tips$s$, $s$default content$s$, TRUE, 0),
  ($s$f8c34df2-8f5d-4d22-ac9c-c58ef455547e$s$, $s$budget_planning$s$, $s$default content$s$, TRUE, 1),
  ($s$f8c34df2-8f5d-4d22-ac9c-c58ef455547e$s$, $s$food_dining$s$, $s$default content$s$, TRUE, 2),
  ($s$f8c34df2-8f5d-4d22-ac9c-c58ef455547e$s$, $s$transportation$s$, $s$default content$s$, TRUE, 3),
  ($s$f8c34df2-8f5d-4d22-ac9c-c58ef455547e$s$, $s$accommodation$s$, $s$default content$s$, TRUE, 4),
  ($s$f8c34df2-8f5d-4d22-ac9c-c58ef455547e$s$, $s$safety_health$s$, $s$default content$s$, TRUE, 5);
-- tips/united-states-new-york
INSERT INTO "tips" ("id", "slug", "country", "country_code", "state", "title", "description", "status", "published_at") VALUES ($s$f0f9b392-4efd-4583-b044-6f9a6d7e4fe2$s$, $s$united-states-new-york$s$, $s$United States$s$, $s$US$s$, $s$New York$s$, $s$United States, New York Travel Tips$s$, $s$Essential tips for traveling in United States, New York$s$, $s$published$s$, '2026-04-12T21:51:34.489Z'::timestamptz);
INSERT INTO "tip_sections" ("tip_id", "section_key", "content", "enabled", "position") VALUES
  ($s$f0f9b392-4efd-4583-b044-6f9a6d7e4fe2$s$, $s$essential_tips$s$, $s$default content$s$, TRUE, 0),
  ($s$f0f9b392-4efd-4583-b044-6f9a6d7e4fe2$s$, $s$budget_planning$s$, $s$default content$s$, TRUE, 1),
  ($s$f0f9b392-4efd-4583-b044-6f9a6d7e4fe2$s$, $s$food_dining$s$, $s$default content$s$, TRUE, 2),
  ($s$f0f9b392-4efd-4583-b044-6f9a6d7e4fe2$s$, $s$transportation$s$, $s$default content$s$, TRUE, 3),
  ($s$f0f9b392-4efd-4583-b044-6f9a6d7e4fe2$s$, $s$accommodation$s$, $s$default content$s$, TRUE, 4),
  ($s$f0f9b392-4efd-4583-b044-6f9a6d7e4fe2$s$, $s$safety_health$s$, $s$default content$s$, TRUE, 5);
