/**
 * One-time gallery import: fetches all images tagged `homePageGallery` from
 * Cloudinary and generates SQL to insert them into the `gallery_images` table.
 *
 * Run with: npx tsx --env-file=.env.local scripts/import-gallery.ts
 *
 * Output: scripts/import-gallery.sql — run this against your Supabase DB.
 * Safe to run multiple times — uses ON CONFLICT DO NOTHING on public_id.
 * Delete this script after the migration is complete.
 */

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

interface CloudinaryResource {
  public_id: string;
  version: number;
  format: string;
  width: number;
  height: number;
  type: string;
  created_at: string;
}

interface CloudinaryListResponse {
  resources: CloudinaryResource[];
}

function escapeSQL(str: string): string {
  return str.replace(/'/g, "''");
}

async function main() {
  console.log("Fetching gallery images from Cloudinary...");

  const res = await fetch("https://res.cloudinary.com/dgfx5h5jl/image/list/homePageGallery.json");
  if (!res.ok) {
    throw new Error(`Cloudinary fetch failed: ${res.status} ${res.statusText}`);
  }

  const data: CloudinaryListResponse = await res.json();
  const images = data.resources;
  console.log(`Found ${images.length} images from Cloudinary.`);

  if (images.length === 0) {
    console.log("No images to import.");
    return;
  }

  const lines: string[] = [
    "-- Auto-generated by scripts/import-gallery.ts",
    "-- Imports Cloudinary homePageGallery images into gallery_images table.",
    "-- Uses ON CONFLICT DO NOTHING so it's safe to run multiple times.",
    "",
    "BEGIN;",
    "",
  ];

  // Start positions after existing rows — use a subquery for max position
  for (let i = 0; i < images.length; i++) {
    const img = images[i];
    const publicId = escapeSQL(img.public_id);
    lines.push(
      `INSERT INTO gallery_images (cloudinary_public_id, position)`,
      `  SELECT '${publicId}', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1`,
      `  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = '${publicId}');`,
      "",
    );
  }

  lines.push("COMMIT;");

  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const outPath = path.join(__dirname, "import-gallery.sql");
  await fs.writeFile(outPath, lines.join("\n"), "utf-8");
  console.log(`\nSQL written to: ${outPath}`);
  console.log(`Run it against your Supabase DB via the SQL Editor or MCP execute_sql.`);
}

main().catch((err) => {
  console.error("Import failed:", err);
  process.exit(1);
});
