-- Auto-generated by scripts/import-gallery.ts
-- Imports Cloudinary homePageGallery images into gallery_images table.
-- Uses ON CONFLICT DO NOTHING so it's safe to run multiple times.

BEGIN;

INSERT INTO gallery_images (cloudinary_public_id, position)
  SELECT 'aroundtheworld50s/homePageGallery/IMG_0407', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1
  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = 'aroundtheworld50s/homePageGallery/IMG_0407');

INSERT INTO gallery_images (cloudinary_public_id, position)
  SELECT 'aroundtheworld50s/homePageGallery/IMG_9775', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1
  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = 'aroundtheworld50s/homePageGallery/IMG_9775');

INSERT INTO gallery_images (cloudinary_public_id, position)
  SELECT 'aroundtheworld50s/homePageGallery/IMG_8991', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1
  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = 'aroundtheworld50s/homePageGallery/IMG_8991');

INSERT INTO gallery_images (cloudinary_public_id, position)
  SELECT 'aroundtheworld50s/homePageGallery/IMG_1361', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1
  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = 'aroundtheworld50s/homePageGallery/IMG_1361');

INSERT INTO gallery_images (cloudinary_public_id, position)
  SELECT 'aroundtheworld50s/homePageGallery/IMG_2424', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1
  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = 'aroundtheworld50s/homePageGallery/IMG_2424');

INSERT INTO gallery_images (cloudinary_public_id, position)
  SELECT 'aroundtheworld50s/homePageGallery/IMG_3937_2', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1
  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = 'aroundtheworld50s/homePageGallery/IMG_3937_2');

INSERT INTO gallery_images (cloudinary_public_id, position)
  SELECT 'aroundtheworld50s/homePageGallery/IMG_0315', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1
  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = 'aroundtheworld50s/homePageGallery/IMG_0315');

INSERT INTO gallery_images (cloudinary_public_id, position)
  SELECT 'aroundtheworld50s/homePageGallery/IMG_9237', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1
  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = 'aroundtheworld50s/homePageGallery/IMG_9237');

INSERT INTO gallery_images (cloudinary_public_id, position)
  SELECT 'aroundtheworld50s/homePageGallery/IMG_5277', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1
  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = 'aroundtheworld50s/homePageGallery/IMG_5277');

INSERT INTO gallery_images (cloudinary_public_id, position)
  SELECT 'aroundtheworld50s/homePageGallery/IMG_1965', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1
  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = 'aroundtheworld50s/homePageGallery/IMG_1965');

INSERT INTO gallery_images (cloudinary_public_id, position)
  SELECT 'aroundtheworld50s/homePageGallery/20171226_102228_Original', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1
  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = 'aroundtheworld50s/homePageGallery/20171226_102228_Original');

INSERT INTO gallery_images (cloudinary_public_id, position)
  SELECT 'aroundtheworld50s/homePageGallery/IMG_4046', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1
  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = 'aroundtheworld50s/homePageGallery/IMG_4046');

INSERT INTO gallery_images (cloudinary_public_id, position)
  SELECT 'aroundtheworld50s/homePageGallery/IMG_3447', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1
  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = 'aroundtheworld50s/homePageGallery/IMG_3447');

INSERT INTO gallery_images (cloudinary_public_id, position)
  SELECT 'aroundtheworld50s/homePageGallery/20180406_145801_Original', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1
  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = 'aroundtheworld50s/homePageGallery/20180406_145801_Original');

INSERT INTO gallery_images (cloudinary_public_id, position)
  SELECT 'aroundtheworld50s/homePageGallery/IMG_9461', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1
  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = 'aroundtheworld50s/homePageGallery/IMG_9461');

INSERT INTO gallery_images (cloudinary_public_id, position)
  SELECT 'aroundtheworld50s/homePageGallery/IMG_9452', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1
  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = 'aroundtheworld50s/homePageGallery/IMG_9452');

INSERT INTO gallery_images (cloudinary_public_id, position)
  SELECT 'aroundtheworld50s/homePageGallery/20180402_131039_Original', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1
  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = 'aroundtheworld50s/homePageGallery/20180402_131039_Original');

INSERT INTO gallery_images (cloudinary_public_id, position)
  SELECT 'aroundtheworld50s/homePageGallery/IMG_6176', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1
  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = 'aroundtheworld50s/homePageGallery/IMG_6176');

INSERT INTO gallery_images (cloudinary_public_id, position)
  SELECT 'aroundtheworld50s/homePageGallery/IMG_0778', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1
  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = 'aroundtheworld50s/homePageGallery/IMG_0778');

INSERT INTO gallery_images (cloudinary_public_id, position)
  SELECT 'aroundtheworld50s/homePageGallery/IMG_0145', COALESCE((SELECT MAX(position) FROM gallery_images), -1) + 1
  WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE cloudinary_public_id = 'aroundtheworld50s/homePageGallery/IMG_0145');

COMMIT;